#pragma once

#include <ATen/ATen.h>

#include "../MaskedPair.h"
#include "../macros.h"
#include "utils/torch_library_utils.h"

// ops declaration macros
#define PT_DECLARE_BINARY_OP(NAME, SELF_T, OTHER_T) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME( \
    SELF_T self, OTHER_T other);

#define PT_DECLARE_BINARY_OP_WITH(NAME, SELF_T, OTHER_T, ARG1) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME(    \
    SELF_T self, OTHER_T other, ARG1);

#define PT_DECLARE_BINARY_OP_WITH2(NAME, SELF_T, OTHER_T, ARG1, ARG2) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME(           \
    SELF_T self, OTHER_T other, ARG1, ARG2);

#define PT_DECLARE_BINARY_OP_WITH3(NAME, SELF_T, OTHER_T, ARG1, ARG2, ARG3) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME(                 \
    SELF_T self, OTHER_T other, ARG1, ARG2, ARG3);

#define PT_DECLARE_BINARY_OP_(NAME, SELF_T, OTHER_T) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME##_( \
    SELF_T self, OTHER_T other);

#define PT_DECLARE_BINARY_OP__WITH(NAME, SELF_T, OTHER_T, ARG1) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME##_(  \
    SELF_T self, OTHER_T other, ARG1);

#define PT_DECLARE_BINARY_OP__WITH2(NAME, SELF_T, OTHER_T, ARG1, ARG2) \
PARTIALTORCH_API c10::intrusive_ptr<TensorMaskedPair> NAME##_(         \
    SELF_T self, OTHER_T other, ARG1, ARG2);

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OP(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>) \
PT_DECLARE_BINARY_OP(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(NAME)                          \
PT_DECLARE_BINARY_OP(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Scalar &)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(NAME)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OP_WITH(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>, ARG1) \
PT_DECLARE_BINARY_OP_WITH(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &, ARG1)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1)                          \
PT_DECLARE_BINARY_OP_WITH(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Scalar &, ARG1)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH(NAME, ARG1)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OP_WITH2(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>, ARG1, ARG2) \
PT_DECLARE_BINARY_OP_WITH2(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2)                          \
PT_DECLARE_BINARY_OP_WITH2(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Scalar &, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH3(NAME, ARG1, ARG2, ARG3) \
PT_DECLARE_BINARY_OP_WITH3(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>, ARG1, ARG2, ARG3) \
PT_DECLARE_BINARY_OP_WITH3(NAME, const_intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &, ARG1, ARG2, ARG3)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OP_(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>) \
PT_DECLARE_BINARY_OP_(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS(NAME)                          \
PT_DECLARE_BINARY_OP_(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const at::Scalar &)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(NAME)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OP__WITH(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>, ARG1) \
PT_DECLARE_BINARY_OP__WITH(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &, ARG1)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1)                          \
PT_DECLARE_BINARY_OP__WITH(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const at::Scalar &, ARG1)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH(NAME, ARG1)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OP__WITH2(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const_intrusive_ptr_arg_t<TensorMaskedPair>, ARG1, ARG2) \
PT_DECLARE_BINARY_OP__WITH2(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const at::Tensor &, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2)                          \
PT_DECLARE_BINARY_OP__WITH2(NAME, intrusive_ptr_arg_t<TensorMaskedPair>, const at::Scalar &, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(NAME)                  \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS(NAME)

#define PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(NAME) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS(NAME)                  \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(NAME)

#define PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1)                  \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH(NAME, ARG1)

#define PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(NAME, ARG1) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(NAME, ARG1)                  \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(NAME, ARG1)

#define PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2)                  \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH2(NAME, ARG1, ARG2)

#define PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2) \
PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2)                  \
PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2(NAME, ARG1, ARG2)

namespace partialtorch {
    namespace ops {
        // logical
        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(bitwise_and)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(bitwise_or)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(bitwise_xor)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(bitwise_left_shift)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(bitwise_right_shift)

        // python logical magic methods
        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__and__)

        PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__iand_)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__or__)

        PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__ior_)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__xor__)

        PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__ixor_)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__lshift__)

        PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__ilshift_)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__rshift__)

        PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS(__irshift_)

        // arithmetics
        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(
                add, const at::Scalar &alpha = 1)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(
                sub, const at::Scalar &alpha = 1)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(
                subtract, const at::Scalar &alpha = 1)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(mul)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(multiply)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(div)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(
                div, c10::optional<c10::string_view> rounding_mode = {})

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(divide)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH(
                divide, c10::optional<c10::string_view> rounding_mode = {})

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(floor_divide)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(true_divide)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(fmod)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(remainder)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(pow)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(float_power)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS(atan2)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS(arctan2)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(logaddexp)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(logaddexp2)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS(nextafter)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS(ldexp)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS_WITH(
                lerp, const at::Scalar &weight)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS_WITH(
                lerp, const at::Tensor &weight)

        // comparison
        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH3(
                isclose, double rtol = 1e-05, double atol = 1e-08, bool equal_nan = false)

        PARTIALTORCH_API bool equal(const_intrusive_ptr_arg_t<TensorMaskedPair> self,
                                    const_intrusive_ptr_arg_t<TensorMaskedPair> other);

        PARTIALTORCH_API bool equal(const_intrusive_ptr_arg_t<TensorMaskedPair> self,
                                    const at::Tensor &other);

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(eq)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(ne)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(not_equal)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(lt)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(less)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(gt)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(greater)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(le)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(less_equal)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(ge)

        PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS(greater_equal)

        // min max
        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(min)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(max)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(minimum)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(maxium)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(fmin)

        PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS(fmax)
    }
}

#undef PT_DECLARE_BINARY_OP
#undef PT_DECLARE_BINARY_OP_WITH
#undef PT_DECLARE_BINARY_OP_WITH2
#undef PT_DECLARE_BINARY_OP_WITH3
#undef PT_DECLARE_BINARY_OP_
#undef PT_DECLARE_BINARY_OP__WITH
#undef PT_DECLARE_BINARY_OP__WITH2
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS_FORALL_TENSOR_OVERLOADS_WITH3
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_OTHER_SCALAR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS
#undef PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH
#undef PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_OVERLOADS_WITH2
#undef PT_DECLARE_BINARY_OPS_AND_OPS__FORALL_TENSOR_AND_SCALAR_OVERLOADS_WITH2
